# Generated by Django 4.1 on 2023-02-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsection',
            old_name='content',
            new_name='Comment',
        ),
    ]
